create user BUG identified by BUG;
alter user BUG quota unlimited on USERS;
/
create or replace function BUG.fun_is_deleted(PID_TIME date)
  return char deterministic is
  begin
    if PID_TIME is null
    then
      return 'N';
    else
      return 'Y';
    end if;
  end;
/
create table BUG.TARGET (
  Id number(38) generated by default as identity,
  DELETED_ON_UTC date
);
/
create index BUG.IDX_TARGET
  on BUG.TARGET (BUG.fun_is_deleted(DELETED_ON_UTC));